### ISSUE TITLE
comp directory missing in v8.0

### ISSUE THREAD

**Issue by ckoern** [conda-forge/geant4-data-emlow-feedstock#17]
### Solution to issue cannot be found in the documentation.

- [X] I checked the documentation.

### Issue

In version 8.0, the `$G4LEDATA/comp` directory is missing, resulting in geant4 v11 to crash. This seems to be fixed in version 8.1, although I don't understand why. The build steps seem to be identical and both datasets directly loaded from the source `https://geant4-data.web.cern.ch/geant4-data/datasets/G4{{ dataset_name }}.{{ version }}.tar.gz` have the `comp` directory present.

As geant4 is pinning it's dependency to `geant4-data-emlow=8.0`, which is the validated dataset for this release, I think it would be helpful to fix this version.

@chrisburr Do you have any idea, why the directory is not present? The sha256 sum in the `meta.yml` is also different from a fresh download from the geant4 homepage. Maybe they silently patched the dataset?

### Installed packages

```shell
# Name                    Version                   Build  Channel
geant4-data-emlow         8.1                  hd8ed1ab_0    conda-forge
```

### Environment info

```shell
active environment : dummy
    active env location : /opt/anaconda3/envs/dummy
            shell level : 4
       user config file : /Users/**/.condarc
 populated config files : /Users/**/.condarc
          conda version : 4.10.1
    conda-build version : 3.20.5
         python version : 3.8.5.final.0
       virtual packages : __osx=10.16=0
                          __unix=0=0
                          __archspec=1=x86_64
       base environment : /opt/anaconda3  (writable)
      conda av data dir : /opt/anaconda3/etc/conda
  conda av metadata url : https://repo.anaconda.com/pkgs/main
           channel URLs : https://conda.anaconda.org/conda-forge/osx-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://repo.anaconda.com/pkgs/main/osx-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/osx-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /opt/anaconda3/pkgs
                          /Users/**/.conda/pkgs
       envs directories : /opt/anaconda3/envs
                          /Users/**/.conda/envs
               platform : osx-64
             user-agent : conda/4.10.1 requests/2.24.0 CPython/3.8.5 Darwin/20.6.0 OSX/10.16
                UID:GID : 504:20
             netrc file : None
           offline mode : False
```

**Comment by chrisburr** [comment]
> The sha256 sum in the meta.yml is also different from a fresh download from the geant4 homepage.

I don't remember exactly and I can't find the issue but There was something weird with the web server not sending the correct headers so the file would be transparently uncompressed causing conda to choose a different checksum.

> Maybe they silently patched the dataset?

This is definitely possible.

> As geant4 is pinning it's dependency to geant4-data-emlow=8.0, which is the validated dataset for this release, I think it would be helpful to fix this version.

I agree: https://github.com/conda-forge/geant4-data-emlow-feedstock/pull/18
